Repository vscode-kubernetes-tools/vscode-kubernetes-tools, pull requests merged in 2024-10, with the labels that each got.

#1208 feat: add an option to disable Helm channel output
  package.json
  src/components/config/config.ts
  src/logger.ts
Labels: enhancement

#1348 Fix typescript update for dependabot and relevant changes.
  package-lock.json
  package.json
  src/components/clusterexplorer/node.folder.resource.ts
  src/components/clusterexplorer/node.resource.ts
Labels: dependencies

#1353 Publish release 1.13.17.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release 🚀

#1355 Fix clipboardy/webpack issue - breaking release 1.3.17
  package-lock.json
  package.json
Labels: bug

#1359 Publish release 1.3.18.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release 🚀

#1361 Simple clipboard implementation.
  package-lock.json
  package.json
  src/components/platform/clipboard.ts
  src/extension.ts
Labels: enhancement

#1369 Fix update with engine udpate.
  package-lock.json
  package.json
Labels: dependencies
