Repository vscode-kubernetes-tools/vscode-kubernetes-tools, pull requests merged in 2024-07, with the labels that each got.

#1279 Fix the ubuntu failure.
  .github/workflows/build-dev.yml
Labels: bug

#1280 Fix/build ev ubuntu failure
  .github/workflows/build-dev.yml
Labels: bug

#1281 Fix for webpack errors/warnings
  webpack.config.js
Labels: bug, dependencies

#1282 Fix the package-ecosystem from empty to npm.
  .github/dependabot.yml
Labels: enhancement, dependencies

#1294 Use `vscode-single-select` instead of `vscode-select`
  src/components/logs/app/index.html
  src/components/logs/app/main.js
Labels: enhancement, dependencies

#1299 fix dependabot build break vscode.
  package-lock.json
  package.json
Labels: dependencies
