Repository vscode-kubernetes-tools/vscode-kubernetes-tools, pull requests merged in 2024-11, with the labels that each got.

#1384 Fix the vscode update.
  package-lock.json
  package.json
Labels: dependencies

#1247 Changes in correlation with new GH Action Permission Changes.
  .github/workflows/build-dev.yml
  .github/workflows/main.yml
Labels: enhancement

#1390 fix the client-node update.
  package-lock.json
  package.json
Labels: dependencies

#1391 Fix:Init container logs not working
  src/components/logs/app/main.js
Labels: bug
