Repository vscode-kubernetes-tools/vscode-kubernetes-tools, pull requests merged in 2025-05, with the labels that each got.

#1537 Add project CNCF logo for this project.
  README.md
  images/k8s-ext-logo/kefvsc-horizontal-colour.png
  images/k8s-ext-logo/kefvsc-horizontal-colour.svg
Labels: enhancement, small, documentation

#1535 Adding check for kubeconfig file path existence
  src/extension.ts
Labels: enhancement

#1538 Update vscode engine and package.
  package-lock.json
  package.json
Labels: dependencies

#1550 Remove invalid badge.
  README.md
Labels: enhancement, maintenance, documentation

#1515 Removing deprecated download package
  package-lock.json
  package.json
  src/components/download/download.ts
  src/components/installer/installdependencies.ts
  src/helm.exec.ts
  tools/save-swagger-enums.js
Labels: enhancement, maintenance

#1552 Work to remove deprecated request package.
  package-lock.json
  package.json
  src/explainer.ts
Labels: enhancement, dependencies
