Repository vscode-kubernetes-tools/vscode-kubernetes-tools, pull requests merged in 2025-04, with the labels that each got.

#1500 Fix: broken telemetry due to old logic in place.
  src/telemetry-helper.ts
Labels: bug, enhancement

#1508 Publish release 1.3.22.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release 🚀

#1470 Potential fix for code scanning alert no. 5: Client-side cross-site scripting
  package.json
  src/components/logs/app/main.js
Labels: enhancement

#1471 Fix some scanning alerts.
  src/kubectlUtils.ts
  src/telemetry-helper.ts
Labels: small

#1516 [Fix] Broken behavior when viewing large pod logs in webview
  src/components/logs/app/main.js
Labels: bug

#1518 [Fix] Error with 'Set kubeconfig'
  src/extension.ts
Labels: bug

#1517 Add bot for stale PR closure
  .github/workflows/close-stale-prs.yml
Labels: enhancement, small

#1520 Fix wrong sub doc.
  src/helm.funcmap.ts
Labels: bug

#1510 Add existing cluster [Fix]
  package-lock.json
  package.json
  src/components/cloudprovider/aksprovider.ts
  src/extension.ts
Labels: bug, enhancement

#1522 Publish release 1.3.23
  .DS_Store
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release 🚀

#1527 [Fix] Log input updating & alignment fix
  src/components/logs/app/index.html
  src/components/logs/app/main.js
Labels: small
