Repository vscode-kubernetes-tools/vscode-kubernetes-tools, pull requests merged in 2025-06, with the labels that each got.

#1565 Adding kebabcase template function to helm linter
  src/helm.funcmap.ts
Labels: small

#1576 Publish release 1.3.24
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release 🚀

#1577 Use recommended Kubernetes metadata labels in snippets
  snippets/ingress.yaml
  snippets/pod.yaml
Labels: small

#1564 Fixing duplicate cluster detection & adding overwrite option
  src/components/kubectl/kubeconfig.ts
Labels: bug, enhancement
