Repository vscode-kubernetes-tools/vscode-kubernetes-tools, pull requests merged in 2025-07, with the labels that each got.

#1595 Publish version 1.3.25
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement

#1594 Detect real CPU arch on macOS to install correct binary
  src/components/installer/installationlayout.ts
Labels: bug, small

#1596 Adding option to disable unwanted Helm notifications
  src/components/config/config.ts
  src/helm.exec.ts
Labels: small

#1609 Fix VSC Engine update and audit.
  package-lock.json
  package.json
Labels: dependencies
