Repository vscode-kubernetes-tools/vscode-kubernetes-tools, pull requests merged in 2025-02, with the labels that each got.

#1445 Publish release 1.3.20
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release 🚀

#1448 remove acs and it's options
  src/components/clusterprovider/azure/azure.ts
  src/components/clusterprovider/azure/azureclusterprovider.ts
Labels: enhancement

#1455 Feat/aks cluster
  package-lock.json
  package.json
  src/components/cloudprovider/aksprovider.ts
  src/components/cloudprovider/cloudprovider.ts
  src/components/clusterprovider/azure/azure.ts
  src/components/clusterprovider/azure/azureclusterprovider.ts
  src/extension.ts
  src/utils/notification.ts
Labels: enhancement

#1468 GH Workflow: Add code ql for the repo.
  .github/workflows/codeql.yml
Labels: enhancement, dependencies

#1463 Fix the type/nodes update.
  package-lock.json
  package.json
  src/components/kubectl/dashboard.ts
Labels: dependencies
